// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaNotasFinal.Models;

#nullable disable

namespace SistemaNotasFinal.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20231017174232_Criacao-SistemaNotasFinal")]
    partial class CriacaoSistemaNotasFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaNotasFinal.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AlunoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdadeAluno")
                        .HasColumnType("int")
                        .HasColumnName("AlunoIdade");

                    b.Property<string>("NomeAluno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AlunoNome");

                    b.Property<string>("SerieAluno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AlunoSerie");

                    b.HasKey("Id");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("SistemaNotasFinal.Models.Bimestre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BimestreId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BimestreAno")
                        .HasColumnType("int")
                        .HasColumnName("AnoBimestre");

                    b.Property<string>("BimestreDescricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BimestreDescricao");

                    b.HasKey("Id");

                    b.ToTable("Bimestre");
                });

            modelBuilder.Entity("SistemaNotasFinal.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MateriaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MateriaNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MateriaNome");

                    b.HasKey("Id");

                    b.ToTable("Materia");
                });

            modelBuilder.Entity("SistemaNotasFinal.Models.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("BimestreId")
                        .HasColumnType("int");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<double>("Notas1")
                        .HasColumnType("float")
                        .HasColumnName("Nota1");

                    b.Property<double>("Notas2")
                        .HasColumnType("float")
                        .HasColumnName("Nota2");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("BimestreId");

                    b.HasIndex("MateriaId");

                    b.ToTable("Nota");
                });

            modelBuilder.Entity("SistemaNotasFinal.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProfessorId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<string>("NomeProfessor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProfessorNome");

                    b.Property<string>("ProfessorFormacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FormacaoProfessor");

                    b.Property<string>("TempoTrabalho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TempoTrabalho");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.ToTable("Professor");
                });

            modelBuilder.Entity("SistemaNotasFinal.Models.Nota", b =>
                {
                    b.HasOne("SistemaNotasFinal.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaNotasFinal.Models.Bimestre", "Bimestre")
                        .WithMany()
                        .HasForeignKey("BimestreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaNotasFinal.Models.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Bimestre");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("SistemaNotasFinal.Models.Professor", b =>
                {
                    b.HasOne("SistemaNotasFinal.Models.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");
                });
#pragma warning restore 612, 618
        }
    }
}
